services:
  postgres:
    image: 'postgres:17.6'
    container_name: url_shortener_postgresql
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - url_shortner_network

networks:
  url_shortner_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local