# port config
server:
  port: 8080

spring:
  application:
    name: Url-Shortner

  # database config
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # jpa config
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    # default value is true, make sure in production make it false or else it will create performance issue.
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql

   # security config
#  security:
#    user:
#      name: user
#      password: pass
#      roles: ADMIN, USER
app:
  baseUrl: http://localhost:8080
  defaultExpiryInDays: 30
  validateOriginalUrl: true
