# port configuration
server:
  port: 8080

spring:
  application:
    name: Url-Shortner

#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true

  # database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # jpa configuration
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true
    # default value is true, make sure in production make it false or else it will create performance issue.
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql

   # security configuration
#  security:
#    user:
#      name: rb
#      password: rb
#      roles:
#        - ADMIN
app:
  baseUrl: http://localhost:8080
  defaultExpiryInDays: 30
  validateOriginalUrl: true
